baseURL = "https://pdbartsch.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "minimal-bootstrap-hugo-theme"


enableGitInfo = false

[taxonomies]
  tag = "tags"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[permalinks]
  post = "/:filename/"

[params]
  description = "Some description"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "800px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-123456789-1"
  cookieConsent = false
  includeBootstrapJs = false

  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]


  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 2

  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 3

  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 4

 
  